### ISSUE TITLE
[DCIC Book]: sets not included

### ISSUE THREAD

**Issue by shriram** [data-centric-computing/dcic-public#19]
### Contact Details

shriram@gmail.com

### Which Web page has the problem?

https://dcic-world.org/2021-08-21/Collections_of_Structured_Data.html

### What's the problem?

This chapter depends on built-in sets, but doesn't say to `include sets`.

**Comment by sorawee** [comment]
FWIW, with `essentials2021`, `include sets` will fail with:

```
The declaration of fold shadows a built-in declaration of the same name.

The declaration of all shadows a built-in declaration of the same name.

The declaration of set shadows a built-in declaration of the same name.

The declaration of any shadows a built-in declaration of the same name.
```

**Comment by kfisler** [comment]
@shriram What do you want me to do about the conflict here? include sets as something and update all the code?

**Comment by shriram** [comment]
@Joe Gibbs Politz ***@***.***> Thoughts on this? I think that's
wisest thing to do. We need sets in only one place…

**Comment by jpolitz** [comment]
For this iteration, yes, kind of has to be `import sets as S` or a different context. The `set` constructor is the painful thing here; `lists.set` (which does functional replace by index, but no curriculum that I know of uses) is included in `essentials2021`.

For `essentials2022`, I think we should hide the list `set` function, and then probably `provide from sets: * hiding (fold, all, any) end` as part of `essentials2022`.

Since we have the `essentials` mechanism (and have other threads where we're considering `dcic` as a context), we won't break existing code, and can clean this up. Without writing a custom context, would be hard to do right now for this bug.
